language: java
sudo: required
addons:
 apt:
  packages:
   - mvn

before_install:
  - ./test/travis/travis-init.sh
  - sudo apt-get install -yq libyaz5-dev

before_script:
 - true

script:
 - mvn install -DskipTests=true
# - mvn test

